export const CHANGE_ROOT_DRAWER_DATA = "CHANGE_ROOT_DRAWER_DATA";
export const GET_ROOT_DRAWER_DATA = "GET_ROOT_DRAWER_DATA";

export const CHANGE_INDEX_ALGORITHMS_DATA = "CHANGE_INDEX_ALGORITHMS_DATA";
export const GET_INDEX_ALGORITHMS_DATA = "GET_INDEX_ALGORITHMS_DATA";

export const CHANGE_INDEX_SELECTED_ALGORITHMS_DATA = "CHANGE_INDEX_SELECTED_ALGORITHMS_DATA";
export const GET_INDEX_SELECTED_ALGORITHMS_DATA = "GET_INDEX_SELECTED_ALGORITHMS_DATA";


