export const CHANGE_ROOT_DRAWER_DATA = "CHANGE_ROOT_DRAWER_DATA";

export const CHANGE_INDEX_ALGORITHMS_DATA = "CHANGE_INDEX_ALGORITHMS_DATA";

export const CHANGE_INDEX_SELECTED_ALGORITHMS_DATA = "CHANGE_INDEX_SELECTED_ALGORITHMS_DATA";

export const CHANGE_INDEX_STEPPER_ACTIVE_STEP_DATA = "CHANGE_INDEX_STEPPER_ACTIVE_STEP_DATA";

export const CHANGE_INDEX_SWITCH_DATASET_DATA = "CHANGE_INDEX_SWITCH_DATASET_DATA";

export const CHANGE_INDEX_OUT_DATA = "CHANGE_INDEX_OUT_DATA";

export const CHANGE_INDEX_FORMS_DATASET_SPECIAL = "CHANGE_INDEX_FORMS_DATASET_SPECIAL";

export const CHANGE_INDEX_FORMS_DATASET_RANDOM = "CHANGE_INDEX_FORMS_DATASET_RANDOM";

export const CHANGE_INDEX_FORMS_DATASET_SEARCHED = "CHANGE_INDEX_FORMS_DATASET_SEARCHED";
